### ISSUE TITLE
sample_capture_hdr.py uses 60 for all three frames

### ISSUE THREAD

**Issue by knatten** [nedrebo/upgraded-funicular#79]
The sample is supposed to use iris `20`, `30`, and `60`. It however ends up using `60`, `60`, and `60`. 

This code tries to set the three different irises:
```python
settings_collection[0].iris = 20
settings_collection[1].iris = 30
settings_collection[2].iris = 60
```

But if you add these three lines below:
```python

print(settings_collection[0].iris)
print(settings_collection[1].iris)
print(settings_collection[2].iris)
```
Then they all print `60`

**Comment by trym-b** [comment]
Made an PR for it:
https://github.com/nedrebo/upgraded-funicular/pull/80
